post http://localhost:3000/registro
Content-Type: application/json

{
  "nombre": "carlos",
  "email": "carlos@gmail.com",
  "password": "123456"
}
###
post http://localhost:3000/registro
Content-Type: application/json

{
  "nombre": "sergio",
  "email": "sergio@gmail.com",
  "password": "123456"
}
###
post http://localhost:3000/registro
Content-Type: application/json

{
  "nombre": "pablo",
  "email": "pablo@gmail.com",
  "password": "123456"
}
###
get http://localhost:3000/login
Content-Type: application/json

{
  "email": "francosfafaf@gmail.com",
  "password": "123456"
}

###
post http://localhost:3000/logout

###
post http://localhost:3000/amigo
Content-Type: application/json

{
  "email": "carlos@gmail.com",
  "amigo": "pablo@gmail.com",
  "nombre": "pablo"
}

###
get http://localhost:3000/amigo
Content-Type: application/json

{
  "email": "carlos@gmail.com"
}