post http://localhost:3000/registro
Content-Type: application/json

{
  "nombre": "franco",
  "email": "francosfafaf@gmail.com",
  "password": "123456"
}
###
get http://localhost:3000/login
Content-Type: application/json

{
  "email": "francosfafaf@gmail.com",
  "password": "123456"
}

###
post http://localhost:3000/logout